"""Add table_number to orders

Revision ID: 2cd71bff3e3c
Revises: 36f87a72ed78
Create Date: 2025-03-16 13:26:56.935573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd71bff3e3c'
down_revision: Union[str, None] = '36f87a72ed78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('table_number', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'table_number')
    # ### end Alembic commands ###
